{{- if .Values.enabled }}
{{- if .Values.cors_proxy }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cors-proxy
  namespace: {{ .Values.kie_sandbox_namespace }}
  labels:
    app: cors-proxy
    app.kubernetes.io/component: cors-proxy
    app.kubernetes.io/instance: cors-proxy
    app.kubernetes.io/name: cors-proxy
    app.kubernetes.io/part-of: cors-proxy-app
    app.openshift.io/runtime-namespace: {{ .Values.kie_sandbox_namespace }}
spec:
  replicas: {{ .Values.cors_proxy.replicas }}
  selector:
    app: cors-proxy
  template:
    metadata:
      labels:
        name: cors-proxy
    spec:
      containers:
      - name: cors-proxy
        image: quay.io/kogito_tooling_bot/cors-proxy-image:{{ .Values.kie_sandbox.version }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
{{- end }}
{{- end }}
