{{- if .Values.enabled }}
{{- if .Values.cors_proxy.route }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: cors-proxy
  namespace: {{ .Values.kie_sandbox_namespace }}
  labels:
    app: cors-proxy
    app.kubernetes.io/component: cors-proxy
    app.kubernetes.io/instance: cors-proxy
    app.kubernetes.io/name: cors-proxy
    app.kubernetes.io/part-of: cors-proxy-app
    app.openshift.io/runtime-version: {{ .Values.kie_sandbox.version }}
spec:
  to:
    kind: Service
    name: cors-proxy
    weight: 100
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
{{- end }}
{{- end }}
