{{- if .Values.enabled }}
{{- if .Values.kie_sandbox_extended_services }}
kind: Service
apiVersion: v1
metadata:
  name: kie-sandbox-extended-services
  namespace: {{ .Values.kie_sandbox_namespace }}
  labels:
    app: kie-sandbox-extended-services
    app.kubernetes.io/component: kie-sandbox-extended-services
    app.kubernetes.io/instance: kie-sandbox-extended-services
    app.kubernetes.io/name: kie-sandbox-extended-services
    app.kubernetes.io/part-of: kie-sandbox-extended-services-app
    app.openshift.io/runtime-version: {{ .Values.kie_sandbox.version }}
spec:
  ports:
    - name: 21345-tcp
      protocol: TCP
      port: 21345
      targetPort: 21345
  type: ClusterIP
  selector:
    app: kie-sandbox-extended-services
    deploymentconfig: kie-sandbox-extended-services
{{- end }}
{{- end }}