{{- if .Values.enabled }}
{{- if .Values.kie_sandbox }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kie-sandbox
  namespace: {{ .Values.kie_sandbox_namespace }}
  labels:
    app: kie-sandbox
    app.kubernetes.io/component: kie-sandbox
    app.kubernetes.io/instance: kie-sandbox
    app.kubernetes.io/name: kie-sandbox
    app.kubernetes.io/part-of: kie-sandbox-app
    app.openshift.io/runtime: js
    app.openshift.io/runtime-namespace: {{ .Values.kie_sandbox_namespace }}
spec:
  replicas: {{ .Values.kie_sandbox.replicas }}
  selector:
    matchLabels:
      app: kie-sandbox
  template:
    metadata:
      labels:
        app: kie-sandbox
        deploymentconfig: kie-sandbox
    spec:
      containers:
        - name: kie-sandbox
          image: quay.io/{{ .Values.kie_sandbox.org }}/kie-sandbox-image:{{ .Values.kie_sandbox.version }}
          env:
            - name: KIE_SANDBOX_EXTENDED_SERVICES_URL
              value: 'http://localhost:21345'
            - name: CORS_PROXY_URL
              value: 'https://cors-proxy-kie-tools-namespace.apps.cluster-vjnz8.vjnz8.sandbox882.opentlc.com' 
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}
{{- end }}